# ----------------------------- SERVICES/DAEMONS ----------------------------- #
$statusBar = uwsm app -- qs
$autoMount = uwsm app -- udiskie
$solaar = uwsm app -- solaar -w hide
# $polkit = systemctl --user start hyprpolkitagent

# -------------------------------- XDG PORTAL -------------------------------- #
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# ----------------------------- GENERAL SERVICES ----------------------------- #
exec-once = $statusBar
exec-once = $autoMount
exec-once = $solaar
# exec-once = $polkit
# exec-once = systemctl start input-remapper

# ------------------------------------ APP ----------------------------------- #
exec-once = uwsm app -- sleep 2 && nextcloud # forced to sleep to appear in tray
exec-once = uwsm app -- sleep 2 && keepassxc # forced to sleep to appear in tray