# ---------------------------------- GENERAL --------------------------------- #
env = SSH_AUTH_SOCK,$XDG_RUNTIME_DIR/ssh-agent.socket

env = XCURSOR_SIZE,24

# XDG specifications
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

# Graphics optimizations
env = WLR_RENDERER,vulkan
env = ELECTRON_OZONE_PLATFORM_HINT,wayland
env = LIBVA_DRIVER_NAME,radeonsi

env = QT_QPA_PLATFORMTHEME,gtk3

# --------------------------------- HYPRLAND --------------------------------- #
env = HYPRCURSOR_SIZE,24