# https://wiki.hyprland.org/Configuring/Variables/#input
input {
    kb_layout = ch
    kb_variant = fr

    follow_mouse = 1

    sensitivity = 0.0 # -1.0 - 1.0, 0 means no modification.
    accel_profile = flat

    touchpad {
        disable_while_typing = false
        natural_scroll = true
    }
}

# See https://wiki.hypr.land/Configuring/Gestures
gesture = 3, horizontal, workspace