# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules
# to find class : hyprctl clients
# Negative lookahead doesnt work. instead use "negative" (ex: check steam rule)

# ---------------------------------- GENERAL --------------------------------- #
windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

windowrule {
    name = xwayland-video-bridge-fixes
    match:class = xwaylandvideobridge

    no_initial_focus = true
    no_focus = true
    no_anim = true
    no_blur = true
    max_size = 1 1
    opacity = 0.0
}

windowrule = render_unfocused on, match:class ^(.*)$ # render unfocused for all windows.

# -------------------------------- FULLSCREEN -------------------------------- #
windowrule = fullscreen on, match:title .*World of Warcraft.*
windowrule = fullscreen on, match:title .*MONSTER HUNTER FRONTIER Z.*
windowrule = fullscreen on, match:class .*steam_app_1086940.* # Baldur's Gate 3
windowrule = fullscreen on, match:class .*steam_app_1245620.* # Elden Ring

# ---------------------------------- TILING ---------------------------------- #
# windowrule = tile, class:.*Dofus.*
windowrule = tile on, match:class .*Wakfu.*


# --------------------------------- FLOATING --------------------------------- #
windowrule = float on, match:class thunderbird, match:title ^(?!Mozilla*)
windowrule = float on, match:class .*Waydroid.*
windowrule = float on, match:class .*pavucontrol.*
windowrule = float on, match:class .*seafile.*
windowrule = float on, match:class .*nextcloud.*
windowrule = float on, match:class .*coolercontrol.*
windowrule = float on, match:class .*keepassxc.*
windowrule = float on, match:class .*blueman-manager.*
windowrule = float on, match:class .*nm-connection-editor.*
windowrule = float on, match:class .*EonTimer.*
windowrule = float on, match:class .*PokeFinder.*
windowrule = float on, match:class steam, match:title negative:^Steam$ # all steam window except main

# ------------------------------- SIZE/POSITION ------------------------------ #
windowrule = size 2542 1378, center 1, match:class .*Dofus.*

# ------------------------ POPUP/DROPDOWN CLOSING FIX ------------------------ #
windowrule = stay_focused on, match:title ^Nextcloud$ # FIXME: causes issue if need to grant access from browser. cannot change focus
# windowrule = min_size 1 1, title:.*Nextcloud.*
# windowrule = stay_focused on, match:class ^zoom$
# windowrule = stayfocused, title:^menu window$, class:^zoom$