stow --target ~ alacritty
stow --target ~ aliases
stow --target ~ hyprland
stow --target ~ mangohud
stow --target ~ mpv
stow --target ~ noctalia
stow --target ~ nvim
stow --target ~ oh-my-posh
stow --target ~ retroarch
stow --target ~ udiskie
stow --target ~ uwsm
stow --target ~ zsh