orientation: normal

rows: 3
columns: 4
knobs: 2

layers:
  - buttons:
      - ["prev", "play", "next", "mute"]
      - ["prev", "play", "next", "mute"]
      - ["prev", "play", "next", "mute"]
    knobs:
      - ccw: "volumedown"
        press: "mute"
        cw: "volumeup"
      - ccw: "volumedown"
        press: "mute"
        cw: "volumeup"
