#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = "{{ .Shell }} in {{ .Folder }}"

[[blocks]]
  type = "prompt"
  alignment = "left"
  newline = true

  [[blocks.segments]]
    type = "path"
    style = "plain"
    foreground = "blue"
    template = "{{ .Path }}"

    [blocks.segments.properties]
      style = "full"

  [[blocks.segments]]
    type = "python"
    style = "plain"
    powerline_symbol = ""
    foreground = "#F5C2E7"
    template = "  {{ .Full }} "

  [[blocks.segments]]
    type = "git"
    style = "plain"
    foreground = "#B4BEFE"
    template = " {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} <cyan>{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}</>"

    [blocks.segments.properties]
      commit_icon = "\uF417 "
      tag_icon = "\uF412 "
      rebase_icon = "\uE728 "
      cherry_pick_icon = "\uE29B "
      revert_icon = "\uF0E2 "
      merge_icon = "\uE727 "
      no_commits_icon = "\uF0C3"
      branch_icon = "\uE725 "
      fetch_upstream_icon = false
      fetch_status = true

[[blocks]]
  type = "prompt"
  alignment = "left"
  newline = true

  [[blocks.segments]]
    type = "text"
    style = "plain"
    foreground_templates = [
      "{{if gt .Code 0}}red{{end}}",
      "{{if eq .Code 0}}magenta{{end}}",
    ]
    template = "❯"

[[blocks]]
  type = "rprompt"
  overflow = "hidden"

  [[blocks.segments]]
    type = "executiontime"
    style = "plain"
    foreground = "yellow"
    template = "{{ .FormattedMs }}"

    [blocks.segments.properties]
      threshold = 5000

[secondary_prompt]
  foreground = "magenta"
  template = "❯❯ "
